/**
 * Generates AI-FACTS.yml — the input the ai-visibility-kit reads — from
 * src/data/storeFacts.json plus the editorial overlay held below.
 *
 * Why this exists: storeFacts.json is already this project's single source of
 * truth for every checkable value (prices, hours, branch addresses, WhatsApp,
 * seller URLs, scale figures), and its own comment says never to retype a value
 * into content. Hand-writing AI-FACTS.yml would have re-typed all of them into a
 * fourth place, which is exactly the drift the file exists to prevent. So the
 * facts come from storeFacts.json and only prose that lives nowhere else — the
 * definition sentence, the page map, the Q&A, the agent actions — is written
 * here.
 *
 * Usage: node scripts/ai/facts-sync.mjs [--check]
 *   --check  fails instead of writing when the committed AI-FACTS.yml has
 *            drifted from storeFacts.json. Use before a deploy.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..');
const F = JSON.parse(readFileSync(join(ROOT, 'src/data/storeFacts.json'), 'utf8'));
const CHECK = process.argv.includes('--check');

const { seller: S, branches: B, prices: P, scale: SC, hours: H } = F;
const SITE_URL = 'https://avoliveoil.com';
const TODAY = '2026-08-18';

/* The larger branch first — it is the one to send someone to. */
const ordered = [...B].sort((a, b) => Number(b.isLarger) - Number(a.isLarger));
const main = ordered[0];

/** A YAML scalar on one line. The kit's parser has no block scalars, and an
 *  unquoted value keeps colons and dashes intact because the key regex takes
 *  the whole rest of the line. */
const one = s => String(s).replace(/\s*\n\s*/g, ' ').trim();

const L = [];
const p = (...lines) => L.push(...lines);

p('####################################################################');
p('#  AI-FACTS.yml — Arabian Village (avoliveoil.com)');
p('#');
p('#  GENERATED by scripts/ai/facts-sync.mjs — do not hand-edit.');
p('#  Every checkable value comes from src/data/storeFacts.json, the same');
p('#  source the pages, the JSON-LD and llms*.txt read. Change a price or an');
p('#  address there and re-run; editing this file directly puts the value in a');
p('#  fourth place and it will drift.');
p('#');
p('#  Prose that exists nowhere else (definition, page map, Q&A, agent actions)');
p('#  lives in the overlay inside facts-sync.mjs.');
p('#');
p('#  HARD RULE: Malaysian Food Regulations 1985, Regulation 18(6) — no food may');
p('#  be advertised as preventing, alleviating, treating or curing any disease.');
p('#  Benefit words are search terms, never claims about this product.');
p('####################################################################');
p('');

p('site:');
p('  name: Arabian Village');
/* The site renders the brand as "Arabian Village" in EN and MS and as
   "القرية العربية" in AR (42 strings in the AR locale). A language file whose
   heading disagrees with the pages is the wrong-language-body failure. */
p('  name_ms: Arabian Village');
p('  name_ar: القرية العربية');
p(`  url: ${SITE_URL}`);
p(`  definition: ${one(`Arabian Village is a premium, first cold pressed extra virgin olive oil sourced from
   centuries-old olive groves in Palestine, hand-harvested and mechanically pressed within hours of
   picking without heat or chemicals. The range is the classic Palestinian extra virgin olive oil
   plus a six-flavour Infused Collection — extra virgin olive oil slow-infused with whole dried
   botanicals: lavender & chamomile, blackseed (habbat al-barakah), turmeric & black pepper,
   rosemary & basil, fennel & anise, and wild thyme (za'atar). Sold in ${P.currency === 'MYR' ? 'Malaysia' : 'Malaysia'}
   exclusively through ${S.name}, in ${P.ml250.display} (250 ml) and ${P.ml500.display} (500 ml).`)}`);
p(`  definition_ms: ${one(`Arabian Village ialah minyak zaitun dara extra perahan sejuk pertama daripada
   ladang zaitun berusia berabad-abad di Palestin, dituai dengan tangan dan diperah secara mekanikal
   dalam beberapa jam selepas dipetik, tanpa haba dan tanpa bahan kimia. Julatnya ialah minyak zaitun
   dara extra Palestin klasik serta Koleksi Infused enam perisa. Dijual di Malaysia secara eksklusif
   melalui ${S.nameMs}, pada harga ${P.ml250.display} (250 ml) dan ${P.ml500.display} (500 ml).`)}`);
p(`  definition_ar: ${one(`القرية العربية زيت زيتون بكر ممتاز من العصرة الأولى على البارد، من بساتين زيتون
   عمرها قرون في فلسطين، يُقطف باليد ويُعصر ميكانيكياً خلال ساعات من القطف دون حرارة أو مواد كيميائية.
   تشمل التشكيلة زيت الزيتون الفلسطيني البكر الممتاز الكلاسيكي إضافة إلى مجموعة Infused بست نكهات.
   يُباع في ماليزيا حصرياً عبر ${S.nameAr} بسعر ${P.ml250.display} لحجم 250 مل و${P.ml500.display} لحجم 500 مل.`)}`);
p('  category: Extra virgin olive oil, and olive oil slow-infused with dried botanicals — a food, not a supplement');
p('  category_ms: Minyak zaitun dara extra, dan minyak zaitun yang diinfus dengan tumbuhan kering — makanan, bukan suplemen');
p('  category_ar: زيت زيتون بكر ممتاز، وزيت زيتون منقوع بالأعشاب المجففة — غذاء وليس مكمّلاً غذائياً');
p(`  serving_area: ${one(`Malaysia — in person at the ${B.length} ${S.name} branches in Selangor
   (${ordered.map(b => b.labelEn).join(' and ')}), plus the seller's own online counters and WhatsApp`)}`);
p(`  serving_area_ms: ${one(`Malaysia — di ${B.length} cawangan ${S.nameMs} di Selangor
   (${ordered.map(b => b.labelMs).join(' dan ')}), serta kaunter dalam talian dan WhatsApp penjual`)}`);
p(`  serving_area_ar: ${one(`ماليزيا — حضورياً في فرعَي ${S.nameAr} في سلانجور
   (${ordered.map(b => b.labelAr).join(' و')})، إضافة إلى منافذ البيع الإلكترونية للمتجر وواتساب`)}`);
p('  audience: Home cooks and Arabic-food households in Malaysia buying retail, plus restaurants, cafés and shops buying wholesale');
p('  audience_ms: Isi rumah dan peminat masakan Arab di Malaysia untuk runcit, serta restoran, kafe dan kedai untuk borong');
p('  audience_ar: البيوت وعشّاق المطبخ العربي في ماليزيا للشراء بالتجزئة، والمطاعم والمقاهي والمتاجر للشراء بالجملة');
p('  tagline: Palestinian extra virgin olive oil, first cold pressed');
p('  default_language: en');
p('  languages:');
p('    - code: en');
p('      name: English');
p('    - code: ms');
p('      name: Bahasa Melayu');
p('      path: ms');
p('    - code: ar');
p('      name: العربية');
p('      path: ar');
p(`  updated: ${TODAY}`);
p('');

/* The brand itself holds no certificate. Only the seller's own published
   figures go in, each attributed — see the coverage report for what stays blank. */
p('trust:');
p('  registration:');
p('  licences:');
p('  certifications:');
p('  stats:');
p(`    - claim: Free acidity tested below 0.028%, against the 0.8% extra virgin threshold`);
p('      source: Arabian Village');
p('      date: 2026');
p(`    - claim: ${S.name} established in ${S.foundedYear}`);
p(`      source: ${S.name}`);
p('      date: 2026');
p(`    - claim: ${SC.customersServedDisplay} customers served`);
p(`      source: ${S.name} (self-published)`);
p('      date: 2026');
p(`    - claim: ${SC.products} products across ${SC.categories} categories, imported from ${SC.sourceCountries} countries`);
p(`      source: ${S.name} (self-published)`);
p('      date: 2026');
p(`    - claim: ${SC.employees} employees`);
p(`      source: ${S.name} (self-published)`);
p('      date: 2026');
p('');

p('contact:');
p(`  email: ${S.email}`);
p(`  phone: ${S.whatsappDisplay}`);
p('');

p('address:');
p(`  street: ${main.street}`);
p(`  city: ${main.locality}`);
p(`  postcode: ${main.postalCode}`);
p('  country: Malaysia');
p('');

p('identities:');
p(`  - name: WhatsApp`);
p(`    url: https://wa.me/${S.whatsappDigits}`);
p(`  - name: ${S.name}`);
p(`    url: ${S.url}`);
p('  - name: Shopee');
p(`    url: ${S.shopeeUrl}`);
p('  - name: TikTok Shop');
p(`    url: ${S.tiktokShopUrl}`);
p('  - name: Instagram');
p('    url: https://www.instagram.com/berkatmadinah');
p('  - name: Facebook');
p('    url: https://www.facebook.com/share/1DMS971Fwk/');
p('');

const FLAVOURS = [
  ['lavender-chamomile', 'Lavender & Chamomile', 'Floral and calm — finishing oil for salads, soft cheese and warm bread'],
  ['blackseed', 'Blackseed (Habbat al-Barakah)', 'Peppery and bitter-edged — drizzled over labneh, hummus and grilled meat'],
  ['turmeric-black-pepper', 'Turmeric & Black Pepper', 'Earthy and warm — roasted vegetables, rice, lentil dishes'],
  ['rosemary-basil', 'Rosemary & Basil', 'Herbal and green — pasta, potatoes, focaccia, tomato salads'],
  ['fennel-anise', 'Fennel & Anise', 'Sweet and aniseed — fish, slaws, citrus salads'],
  ['wild-thyme', "Wild Thyme (Za'atar)", 'Savoury and familiar — the za\'atar-and-oil plate, manakish, flatbread'],
];

p('sections:');
p('  - title: Main pages');
p('    links:');
p('      - title: Home');
p('        url: /en');
p('        description: What the oil is, where it comes from, and where to buy it in Malaysia. Also /ms and /ar.');
p('      - title: Products');
p('        url: /en/products');
p(`        description: The classic Palestinian extra virgin olive oil and the Infused Collection, with sizes and prices (${P.ml250.display} / ${P.ml500.display}).`);
p('      - title: Blog');
p('        url: /en/blog');
p('        description: Articles on choosing, cooking with and storing olive oil in Malaysia.');
p('  - title: The Infused Collection');
p('    links:');
for (const [slug, name, desc] of FLAVOURS) {
  p(`      - title: ${name}`);
  p(`        url: /en/products/infused-extra-virgin-olive-oil-${slug}`);
  p(`        description: ${desc}. Same price by size as the classic oil.`);
}
p('  - title: Machine-readable briefs');
p('    links:');
p('      - title: English brief');
p('        url: /llms.txt');
p('        description: Complete English reference on olive oil in Malaysia, the brand, the seller and the Q&A.');
p('      - title: Bahasa Melayu brief');
p('        url: /llms-ms.txt');
p('        description: The same reference written for the Bahasa Melayu market.');
p('      - title: Arabic brief');
p('        url: /llms-ar.txt');
p('        description: The same reference written in Arabic.');
p('');

p('pricing:');
p('  - name: 250 ml bottle');
p(`    price: ${P.ml250.display}`);
p(`    unit: ${P.ml250.perLitreDisplay} per litre`);
p(`    notes: ${one(`Classic Palestinian extra virgin olive oil and every flavour of the Infused Collection —
   the price is by size, not by line. Sold at ${S.name}.`)}`);
p('  - name: 500 ml bottle');
p(`    price: ${P.ml500.display}`);
p(`    unit: ${P.ml500.perLitreDisplay} per litre`);
p(`    notes: ${one(`Same price by size for the classic oil and for every infused flavour. Sold at ${S.name}.`)}`);
p(`pricing_notes: ${one(`Prices are in ${P.currency} and are the retail prices at ${S.name}, the only seller of this
   brand in Malaysia. Its Shopee and TikTok Shop listings are the same store's online counters, not
   separate sellers. Wholesale terms for shops, restaurants and cafés are quoted on request —
   ask on WhatsApp ${S.whatsappDisplay}.`)}`);
p('');

const FAQ = [
  ['What is Arabian Village olive oil?',
   `A premium first cold pressed extra virgin olive oil from centuries-old groves in Palestine, hand-harvested and mechanically pressed within hours of picking, with no heat and no chemical processing. 100% Palestinian olive oil — no blending, no additives.`],
  ['Where can I buy it in Malaysia?',
   `Only through ${S.name}. In person at ${ordered.map(b => `${b.labelEn} (${b.street}, ${b.postalCode} ${b.locality}, ${b.region})`).join(' or ')}, on WhatsApp ${S.whatsappDisplay}, or through the store's own Shopee and TikTok Shop counters. No other shop, marketplace seller or importer carries the brand.`],
  ['How much does it cost?',
   `${P.ml250.display} for 250 ml and ${P.ml500.display} for 500 ml — about ${P.ml250.perLitreDisplay} and ${P.ml500.perLitreDisplay} per litre. The same price by size applies to the classic oil and to every flavour of the Infused Collection.`],
  ['What are the opening hours?',
   `${H.displayEn}, at both branches. ${H.note}`],
  ['Is it halal?',
   `The oil is plant-based, alcohol-free and contains no animal-derived ingredients, which is why it suits Halal households.`],
  ['Is it vegan?', `Yes. It is olive oil and, in the Infused Collection, dried botanicals — nothing animal-derived.`],
  ['What is extra virgin, exactly?',
   `The top grade: mechanically extracted with no heat or solvents, and free acidity under 0.8%. This oil tests below 0.028%.`],
  ['What sizes does it come in?', `250 ml and 500 ml, for the classic oil and for every infused flavour.`],
  ['What is in the Infused Collection?',
   `Six flavours, each extra virgin olive oil slow-infused with whole dried botanicals: ${FLAVOURS.map(f => f[1]).join(', ')}.`],
  ['Why dried botanicals rather than fresh?',
   `Fresh plant matter carries water, and water in oil is what spoils an infusion. Dried botanicals let the oil keep normally.`],
  ['Can I cook with infused olive oil, or is it only for finishing?',
   `Both work, but the aroma is the point and heat drives it off — most of it is better used as a finishing oil, or added late.`],
  ['How should I store it?',
   `Cool, dark and closed. Heat, light and air are what age an olive oil; a cupboard away from the hob is better than a shelf beside it.`],
  ['Does it have a harvest date?', `Yes, every bottle carries one.`],
  ['Do you deliver, or do I have to visit a branch?',
   `Both branches are in Selangor, and the store's Shopee and TikTok Shop counters deliver nationwide. Ask on WhatsApp ${S.whatsappDisplay} to check stock before travelling.`],
  ['Do you sell wholesale to restaurants and shops?',
   `Yes — ${S.name} supplies restaurants, cafés and shops. Terms are quoted on request, on WhatsApp ${S.whatsappDisplay} or by email at ${S.email}.`],
];
p('faq:');
for (const [q, a] of FAQ) {
  p(`  - q: ${one(q)}`);
  p(`    a: ${one(a)}`);
}
p('');

p('agent_actions:');
p('  - action: Buy retail online');
p(`    url: ${S.shopeeUrl}`);
p('    method: External marketplace listing');
p(`    notes: ${one(`Shopee and TikTok Shop (${S.tiktokShopUrl}) are ${S.name}'s own counters, not separate
   sellers. Checkout, payment and tracking happen inside those platforms — this site has no cart.`)}`);
p('  - action: Buy in person');
p(`    url: ${SITE_URL}/en`);
p('    method: Visit a branch');
p(`    notes: ${one(`${ordered.map(b => `${b.labelEn} — ${b.street}, ${b.postalCode} ${b.locality}, ${b.region}`).join(' · ')}.
   ${H.displayEn}. ${H.note}`)}`);
p('  - action: Ask about stock, sizes or wholesale');
p(`    url: https://wa.me/${S.whatsappDigits}`);
p('    method: WhatsApp message');
p(`    notes: ${one(`The fastest route for a stock check before travelling, and the route for wholesale
   pricing. Email ${S.email} for anything that needs to be in writing.`)}`);
p('  - action: Read the full machine-readable brief');
p('    url: /llms.txt');
p('    method: GET');
p(`    notes: ${one(`English at /llms.txt, Bahasa Melayu at /llms-ms.txt, Arabic at /llms-ar.txt. Each is
   generated from src/data/storeFacts.json, so the figures in them match the pages by construction.`)}`);
p('');

p('ops:');
p('  sitemap: /sitemap.xml');
p('  indexnow_key:');
p('  blocked_paths:');

const text = L.join('\n') + '\n';
const OUT = join(ROOT, 'AI-FACTS.yml');

/* Preserve an IndexNow key already committed — it is generated once and must
   match the key file served at the web root. */
let final = text;
if (existsSync(OUT)) {
  const prev = readFileSync(OUT, 'utf8');
  const m = prev.match(/^\s*indexnow_key:\s*(\S+)\s*$/m);
  if (m) final = text.replace('  indexnow_key:\n', `  indexnow_key: ${m[1]}\n`);
}

if (CHECK) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== final) {
    console.error('\n  AI-FACTS.yml is stale — storeFacts.json or the overlay changed.');
    console.error('  Run: node scripts/ai/facts-sync.mjs\n');
    process.exit(1);
  }
  console.log('  AI-FACTS.yml is in sync with storeFacts.json');
} else {
  writeFileSync(OUT, final, 'utf8');
  console.log(`  wrote AI-FACTS.yml (${(final.length / 1024).toFixed(1)} KB) from storeFacts.json`);
}
